# roles/launch_proxy/tasks/main.yml

- name: Launch Nginx container as proxy
  docker_container:
    name: proxy
    image: nginx:latest
    state: started
    restart_policy: always
    networks:
      - my_network
    ports:
      - "80:80"
    volumes:
      - /path/to/nginx.conf:/etc/nginx/nginx.conf:ro

