- hosts: all
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python

  roles:
    - install_docker
    - create_network
    - launch_database
    - launch_app
    - launch_proxy

