name: CI devops 2024
on:
  # Launch the job on pushes to the main and develop branches
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Checkout your GitHub code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

      # Set up JDK 17 using actions/setup-java@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Debug - List files and directories
        run: ls -R
      
      - name: Check if simple-api exists
        run: |
          ls -l $GITHUB_WORKSPACE/simple-api


      
      - name: Verify presence of pom.xml
        run: ls $GITHUB_WORKSPACE/simple-api/pom.xml


      # Build and test the app using Maven
      - name: Build and test with Maven
        run: |
          cd $GITHUB_WORKSPACE/simple-api
          mvn clean install
  build-and-push-docker-image:
    needs: test-backend 
    runs-on: ubuntu-22.04

    steps:
      # Cloner le code
      - name: Checkout code
        uses: actions/checkout@v2.5.0
      
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
        #run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Construire l'image Docker pour le backend
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api  # Chemin vers le Dockerfile pour le backend
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Construire l'image Docker pour la base de données (database)
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database  # Chemin vers le Dockerfile pour la base de données
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Construire l'image Docker pour le serveur HTTP (httpd)
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./http-server  # Chemin vers le Dockerfile pour le serveur HTTP
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
      
      

